/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.blogspot.denisbenjamim.componentes.painel;

import java.util.Calendar;

/**
 *
 * @author denis.benjamim
 */
public class JDataHora extends javax.swing.JPanel {

    /**
     * Creates new form DataHora
     */
    public JDataHora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDC_data = new com.toedter.calendar.JDateChooser();
        jSF_hora = new com.toedter.components.JSpinField();
        jSF_minuto = new com.toedter.components.JSpinField();

        setLayout(new java.awt.GridLayout(1, 0));

        jDC_data.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        jDC_data.setDate(Calendar.getInstance().getTime());
        jDC_data.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jDC_data);

        jSF_hora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        jSF_hora.setMaximum(24);
        jSF_hora.setMinimum(1);
        jSF_hora.setValue(Calendar.getInstance().get(Calendar.HOUR_OF_DAY));
        add(jSF_hora);

        jSF_minuto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Minuto:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        jSF_minuto.setMaximum(59);
        jSF_minuto.setMinimum(0);
        jSF_minuto.setValue(Calendar.getInstance().get(Calendar.MINUTE));
        add(jSF_minuto);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDC_data;
    private com.toedter.components.JSpinField jSF_hora;
    private com.toedter.components.JSpinField jSF_minuto;
    // End of variables declaration//GEN-END:variables

    public com.toedter.calendar.JDateChooser getjDC_data() {
        return jDC_data;
    }

    public com.toedter.components.JSpinField getjSF_hora() {
        return jSF_hora;
    }

    public com.toedter.components.JSpinField getjSF_minuto() {
        return jSF_minuto;
    }
}
